# Site settings
title: "Elizabeth Ramos Vieira"
description: "Elizabeth Ramos Vieira"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Elizabeth Ramos Vieira"
resume_title:                   "Junior Web Developer"
resume_contact_email:           "elizabethlopesramos@gmail.com"
resume_contact_telephone:       "11 94521-8600"
resume_contact_address:         "Rua Brigadeiro Galv達o, 322 - ap 13. Barra Funda - S達o Paulo"
resume_header_contact_info: "Rua Brigadeiro Galv達o, 322 - S達o Paulo | 11 94521-8600 | elizabethlopesramos@gmail.com"
resume_header_intro: "<p>I currently work as a Junior Web Developer, with a focus on the Ruby language and Rails Framework. But I also have 5 years of experience with the banking industry. I Was a digital account manager.
                         I was responsible for a portfolio of 1.200 clients with medium-high income profile. My main asset was to offer specialized an personalized service, doing an individual analysis of each one, with the
                         purpose of leveraging their rent and segment according to their profile.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/elizabethramos"
  resume_twitter_url:           "http://twitter.com/elizaramosv"
  resume_dribbble_url:          "https://elizabethramos.github.io/about-me/"
  resume_facebook_url:          "https://www.facebook.com/elizaclr"
  resume_linkedin_url:          "https://www.linkedin.com/in/elizabeth-ramos/"
  # resume_website_url:           ""
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
